server {
    listen 80;
    listen [::]:80;

    server_name _;

    root /home/hachimi/project/robotics-course/site;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
